apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-app-ingress
spec:
  rules:
    - host: nambrosini.xyz
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: example-app
              port:
                number: 80
