apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    - nambrosini.xyz
  secretName: example-app-certificate
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer